---
dependencies: []

galaxy_info:
  author: Vinod Panicker
  description: Git for OAH
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - development
    - system
